config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  get 'products/:product_id/donate', to: 'charges#prepare'
  post 'products/:product_id/charges/new', to: 'charges#new'


  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :charges
  end


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch

  before_validation :set_end_time
  pg_search_scope :search, against: [:title, :description],
                  using: {tsearch: {dictionary: 'english', prefix: true, any_word: true, negation: true}},
                  associated_against: { user: :username }

  belongs_to :user
  validates :target, presence: true, numericality: true
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true


  def update_total(amount)
    amount = total + amount unless total.nil?
    self.update_attributes(total: amount)
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      all.order('created_at DESC')
    end
  end


  private

  def set_end_time
    self.end_time = Time.now + 30.days
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products       

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new session['devise.user_attributes'] do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
  end

  def create
    @product = Product.find(params[:product_id])
    @amount = params[:amount]

    @amount = @amount.gsub('$', '').gsub(',', '')

    begin
      @amount = Float(@amount).round(2)
    rescue
      flash[:danger] = 'Charge not completed. Please enter a valid amount in USD($).'
      redirect_to new_product_charge_path(@product)
      return
    end

    @amount = (@amount * 100).to_i # Must be an integer!

    if @amount < 500
      flash[:danger] = 'Charge not completed. Donation amount must be at least $5.'
      redirect_to new_product_charge_path(@product)
      return
    end

    Stripe::Charge.create(
      :amount => @amount,
      :currency => 'usd',
      :source => params[:stripeToken],
      :description => "Donation to #{@product.title}"
    )
    @product.update_total(@amount/100)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_product_charge_path(@product)
    end

  end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.persisted?
      flash[:notice] = "Welcome back #{user.username}"
      sign_in_and_redirect user
    else
      session['devise.user_attributes'] = user.attributes
      redirect_to new_user_registration_path
    end
  end

  alias_method :twitter, :all
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @products = Product.text_search(params[:query]).page(params[:page]).per_page(3)
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      AlertWorker.perform_in(5.minutes, @product.id)
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
    if @product.save
      redirect_to products_path
    else
      flash[:danger] = 'Something wrong with your form'
      render 'edit'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = 'Fund deleted successfully'
    redirect_to products_path
  end


  private

  def product_params
    params.require(:product).permit(:description, :title, :target)
  end

  def authenticate_admin!
    redirect_to root_url unless current_user.admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def flash_class_name(name)
    case name
    when 'notice' then 'success'
    when 'alert'  then 'danger'
    else name
    end
  end

  def percentage(product)
    product.total.nil? ? 0 : (product.total/product.target)*100
  end
end

app/views/charges/_form.html.erb
<%= form_tag product_charges_path(@product) do %>
  <div id="error_explanation">
    <% if flash[:danger].present? %>
      <p class='alert alert-danger'><%= flash[:danger] %></p>
    <% end %>
  </div>
  <article>
    <div class='form-group'>
      <%=label_tag :amount, "How much do you want to donate?"%>
      <div class="input-group">
        <div class="input-group-addon">$</div>
        <%=text_field_tag(:amount, "", class: 'form-control')%>
        <div class="input-group-addon">.00</div>
      </div>
    </div>
  </article>
  <article>
    <%= hidden_field_tag(:stripeToken) %>
  </article>
  <button id='donateButton' class='btn btn-primary pull-right'>Donate</button>
<% end %>

app/views/charges/create.html.erb
<h2>Thank you!</h2>
<p>Your donation of <strong><%= number_to_currency(@amount * 0.01) %></strong>
 has been received.</p>

app/views/charges/new.html.erb
<div class='row'>
  <div class='col-md-4 col-md-offset-1'>
    <%=render 'form' %>
  </div>
  <div class='col-md-5 col-md-offset-1'>
    <%=render partial: 'products/product_info', locals: {product: @product} %>
  </div>
</div>

<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
var handler = StripeCheckout.configure({
  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
  locale: 'auto',
  name: '<%=@product.title%>',
  description: 'One-time donation',
  token: function(token) {
    $('input#stripeToken').val(token.id);
    $('form').submit();
  }
});
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Yaoie's Fund", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%=link_to "Start a campaign", new_product_path if current_user.admin? %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%=link_to "Edit profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%=link_to "Logout", destroy_user_session_path, method: :delete %>
            </ul>
          </li>
        <% else %>
          <li><%=link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
      <%=form_tag products_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%=text_field_tag :query, params[:query], class: "form-control" %>
        </div>
        <%=submit_tag('Search', class: "btn btn-primary") %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class='container'>
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= flash_class_name(name) %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%=msg%>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%=form_for @product do |f| %>
  <%=render 'shared/error_messages', object: @product%>

  <div class='form-group'>
    <%=f.label :title %></br>
    <%=f.text_field :title, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%=f.label :description %></br>
    <%=f.text_area :description, class:'form-control', rows: 7 %>
  </div>

  <div class='form-group'>
    <%=f.label :target, 'Target amount' %>
    <div class="input-group">
      <div class="input-group-addon">$</div>
        <%=f.text_field :target, class:'form-control' %>
        <div class="input-group-addon">.00</div>
    </div>
  </div>

  <%=f.submit 'Submit', class:'btn btn-primary pull-right' %>
  <%=link_to 'Cancel', root_path, class:'btn btn-default' %>

<% end %>

app/views/products/_product.html.erb
<div class='list-group'>
  <%=link_to product_path(product), class: 'list-group-item' do %>
    <h4 class='list-group-item-heading'><%=product.title %> (<%=number_to_currency(product.target, precision: 0)%>)</h4>
    <p class="list-group-item-text">
      <%=truncate(product.description, :length => 500, :seperator => '')%>
    </p>
  <% end %>
  <div class='pull-right'>
    <% if current_user.try(:admin?) %>
      <span><%=link_to 'Edit', edit_product_path(product) %></span>
      <span><%=link_to 'Delete', product_path(product), method: :delete %></span>
    <% end %>
  </div>
</div>

app/views/products/_product_info.html.erb
<%=link_to product_path(product) do %>
  <div class="thumbnail">
    <%=image_tag('default', height: 267, width: 400) %>
    <div class="caption">
      <h3><%=product.title%>(<%=number_to_currency(product.target, precision: 0)%>)</h3>
      <p>by <%=product.user.username %></p>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<%=render 'form' %>

app/views/products/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <%=render @products %>
  <%=will_paginate @products%>
</div>

app/views/products/new.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>
    <%=render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <div class='row'>
      <div class='col-md-6'>
        <blockquote>
          <h1><%=@product.title %></h1>
          <footer>by <%=@product.user.username%></footer>
        </blockquote>
        <p><%=simple_format @product.description%></p>
      </div>
      <div class='col-md-5 col-md-offset-1'>
        <div class="thumbnail">
          <%=image_tag('default', width: 400, height: 267) %>
          <div class="caption">
            <h4> Percentage to target (<%=number_to_currency(@product.total,precision: 0)%> / <%=number_to_currency(@product.target,precision: 0)%>)</h4>
            <div class="progress">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-
              valuenow="<%=percentage(@product)%>" aria-valuemin="0" aria-
              valuemax="100" style='min-width: 2em; width:<%=number_to_percentage(percentage(@product),precision: 0)%>;'>
                <%=number_to_percentage(percentage(@product), precision: 0) %>
              </div>
            </div>
            <%=link_to 'Donate', new_product_charge_path(@product), class:'btn btn-primary btn-block'%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% for message in object.errors.full_messages %>
      <%= message %>
    <% end %>
  </div>
<% end %>